{
 "title": "SUBSTRATE | DOUBLETOP",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "label": "Server Job",
    "query": {
     "query": "label_values(substrate_block_height{owner=~\"$owner\"}, job)"
    }
   },
   {
    "name": "owner",
    "label": "Owner",
    "query": {
     "query": "label_values(substrate_block_height,owner)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(substrate_block_height{job=~\"$job\",owner=~\"$owner\"},instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(substrate_block_height{job=~\"$job\", owner=~\"$owner\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Block Finalized",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_block_height{instance=\"$node\",status=~\"finalized|sync_target\",owner=\"$owner\"}",
     "legendFormat": "{{instance}} {{status}}"
    }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total{instance=\"$node\",owner=\"$owner\"}[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Block rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_block_height{status=\"finalized\",instance=\"$node\",owner=\"$owner\"}[10m])*60",
     "legendFormat": "{{instance}}  Blocks / minute"
    }
   ]
  },
  {
   "title": "TXs Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "{{instance}}",
     "target": "txcount",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Peers count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{instance=\"$node\",owner=\"$owner\"}"
    }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "queued_blocks"
    }
   ]
  },
  {
   "title": "Relative Block Production Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_block_height{status=\"finalized\",instance=\"$node\",owner=\"$owner\"}[10m])/rate(substrate_block_height{status=\"finalized\",instance=\"$node\",owner=\"$owner\"}[1m])",
     "legendFormat": "rate[10m] / rate[1m]"
    }
   ]
  },
  {
   "title": "Blocks Av per min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(substrate_block_height{instance=\"$node\",status=~\"finalized|sync_target\",owner=\"$owner\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Diff -> ( Best Block - Finalized )",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(substrate_block_height{status=\"best\",instance=\"$node\",owner=\"$owner\"})-scalar(substrate_block_height{status=\"finalized\",instance=\"$node\",owner=\"$owner\"})",
     "legendFormat": "[[hostname]]"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total{instance=\"$node\",owner=\"$owner\"}[1m]) - rate(substrate_tasks_polling_duration_count{instance=\"$node\",owner=\"$owner\"}[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "sub_libp2p",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_connections{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "{{instance}} connections"
    },
    {
     "expr": "substrate_sub_libp2p_is_major_syncing{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "{{instance}} syncing"
    },
    {
     "expr": "substrate_sub_libp2p_kbuckets_num_nodes{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "{{instance}} num_nodes"
    }
   ]
  },
  {
   "title": "Sync justifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sync_extra_justifications{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "substrate_sync_extra_justifications_failed{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "{{instance}} failed"
    },
    {
     "expr": "substrate_sync_extra_justifications_importing{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "{{instance}} importing"
    },
    {
     "expr": "substrate_sync_extra_justifications_pending{instance=\"$node\",owner=\"$owner\"}",
     "legendFormat": "{{instance}} pending"
    }
   ]
  },
  {
   "title": "GRANDPA Validator Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_communication_gossip_validator_messages{instance=\"$node\",owner=\"$owner\"}[5m])",
     "legendFormat": "{{message}}"
    }
   ]
  }
 ]
}